// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MondayFunday.Database;

#nullable disable

namespace MondayFunday.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323100930_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MondayFunday.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jewelery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jewelery"
                        });
                });

            modelBuilder.Entity("MondayFunday.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Name = "Ergonomic Steel Cheese",
                            Price = 513.07m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Name = "Refined Wooden Fish",
                            Price = 263.66m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Intelligent Cotton Bike",
                            Price = 25.69m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Handmade Concrete Salad",
                            Price = 860.93m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Ergonomic Granite Pants",
                            Price = 708.26m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Generic Soft Fish",
                            Price = 398.87m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Handcrafted Concrete Hat",
                            Price = 487.48m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Licensed Steel Shoes",
                            Price = 450.27m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Name = "Handmade Cotton Ball",
                            Price = 286.34m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Name = "Incredible Cotton Pizza",
                            Price = 179.61m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Name = "Generic Rubber Table",
                            Price = 498.72m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Name = "Awesome Metal Car",
                            Price = 930.08m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Name = "Ergonomic Cotton Pants",
                            Price = 19.87m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Small Fresh Fish",
                            Price = 768.40m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Name = "Handmade Metal Table",
                            Price = 377.39m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Name = "Handcrafted Concrete Car",
                            Price = 76.83m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Name = "Gorgeous Fresh Towels",
                            Price = 545.79m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Name = "Ergonomic Soft Chair",
                            Price = 457.56m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Name = "Ergonomic Frozen Towels",
                            Price = 274.39m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Gorgeous Wooden Ball",
                            Price = 465.60m
                        });
                });

            modelBuilder.Entity("MondayFunday.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "this product is brown.",
                            ProductId = 2,
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            Comment = "My co-worker Bryton has one of these. He says it looks ragged.",
                            ProductId = 11,
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            Comment = "My neighbor Isabela has one of these. She works as a taxidermist and she says it looks monochromatic.",
                            ProductId = 4,
                            Rating = 2
                        },
                        new
                        {
                            Id = 4,
                            Comment = "i use it until further notice when i'm in my station.",
                            ProductId = 11,
                            Rating = 2
                        },
                        new
                        {
                            Id = 5,
                            Comment = "this product is dominant.",
                            ProductId = 5,
                            Rating = 1
                        },
                        new
                        {
                            Id = 6,
                            Comment = "i use it until further notice when i'm in my nightclub.",
                            ProductId = 15,
                            Rating = 5
                        },
                        new
                        {
                            Id = 7,
                            Comment = "The box this comes in is 3 kilometer by 5 inch and weights 13 ton.",
                            ProductId = 18,
                            Rating = 1
                        },
                        new
                        {
                            Id = 8,
                            Comment = "The box this comes in is 3 kilometer by 5 inch and weights 13 ton.",
                            ProductId = 11,
                            Rating = 4
                        },
                        new
                        {
                            Id = 9,
                            Comment = "It only works when I'm Singapore.",
                            ProductId = 12,
                            Rating = 4
                        },
                        new
                        {
                            Id = 10,
                            Comment = "This product works certainly well. It accidentally improves my baseball by a lot.",
                            ProductId = 15,
                            Rating = 2
                        },
                        new
                        {
                            Id = 11,
                            Comment = "i use it usually when i'm in my alley.",
                            ProductId = 14,
                            Rating = 3
                        },
                        new
                        {
                            Id = 12,
                            Comment = "My peacock loves to play with it.",
                            ProductId = 10,
                            Rating = 4
                        },
                        new
                        {
                            Id = 13,
                            Comment = "I saw one of these in Spratly Islands and I bought one.",
                            ProductId = 1,
                            Rating = 3
                        },
                        new
                        {
                            Id = 14,
                            Comment = "My neighbor Montserrat has one of these. She works as a circus performer and she says it looks shriveled.",
                            ProductId = 10,
                            Rating = 3
                        },
                        new
                        {
                            Id = 15,
                            Comment = "My porcupine loves to play with it.",
                            ProductId = 6,
                            Rating = 4
                        },
                        new
                        {
                            Id = 16,
                            Comment = "The box this comes in is 5 light-year by 6 foot and weights 17 megaton!!!",
                            ProductId = 6,
                            Rating = 5
                        },
                        new
                        {
                            Id = 17,
                            Comment = "heard about this on ndombolo radio, decided to give it a try.",
                            ProductId = 4,
                            Rating = 4
                        },
                        new
                        {
                            Id = 18,
                            Comment = "This product works too well. It buoyantly improves my football by a lot.",
                            ProductId = 13,
                            Rating = 3
                        },
                        new
                        {
                            Id = 19,
                            Comment = "I saw one of these in Tanzania and I bought one.",
                            ProductId = 1,
                            Rating = 4
                        },
                        new
                        {
                            Id = 20,
                            Comment = "talk about remorse!!!",
                            ProductId = 2,
                            Rating = 1
                        },
                        new
                        {
                            Id = 21,
                            Comment = "This product works so well. It hungrily improves my basketball by a lot.",
                            ProductId = 2,
                            Rating = 2
                        },
                        new
                        {
                            Id = 22,
                            Comment = "My co-worker Rey has one of these. He says it looks uneven.",
                            ProductId = 1,
                            Rating = 1
                        },
                        new
                        {
                            Id = 23,
                            Comment = "My neighbor Lonnie has one of these. She works as a hobbit and she says it looks microscopic.",
                            ProductId = 18,
                            Rating = 4
                        },
                        new
                        {
                            Id = 24,
                            Comment = "My neighbor Frona has one of these. She works as a gambler and she says it looks bearded.",
                            ProductId = 8,
                            Rating = 4
                        },
                        new
                        {
                            Id = 25,
                            Comment = "The box this comes in is 3 yard by 6 yard and weights 19 pound!!!",
                            ProductId = 9,
                            Rating = 4
                        },
                        new
                        {
                            Id = 26,
                            Comment = "My terrier loves to play with it.",
                            ProductId = 14,
                            Rating = 1
                        },
                        new
                        {
                            Id = 27,
                            Comment = "My ant loves to play with it.",
                            ProductId = 2,
                            Rating = 2
                        },
                        new
                        {
                            Id = 28,
                            Comment = "one of my hobbies is gaming. and when i'm gaming this works great.",
                            ProductId = 18,
                            Rating = 3
                        },
                        new
                        {
                            Id = 29,
                            Comment = "this product is brown.",
                            ProductId = 13,
                            Rating = 4
                        },
                        new
                        {
                            Id = 30,
                            Comment = "This product works certainly well. It energetically improves my golf by a lot.",
                            ProductId = 1,
                            Rating = 4
                        },
                        new
                        {
                            Id = 31,
                            Comment = "talk about contempt!",
                            ProductId = 2,
                            Rating = 3
                        },
                        new
                        {
                            Id = 32,
                            Comment = "This product works excessively well. It speedily improves my baseball by a lot.",
                            ProductId = 6,
                            Rating = 2
                        },
                        new
                        {
                            Id = 33,
                            Comment = "My chicken loves to play with it.",
                            ProductId = 3,
                            Rating = 3
                        },
                        new
                        {
                            Id = 34,
                            Comment = "This product works very well. It persistently improves my soccer by a lot.",
                            ProductId = 13,
                            Rating = 4
                        },
                        new
                        {
                            Id = 35,
                            Comment = "My co-worker Cato has one of these. He says it looks sopping.",
                            ProductId = 2,
                            Rating = 1
                        },
                        new
                        {
                            Id = 36,
                            Comment = "i use it barely when i'm in my store.",
                            ProductId = 19,
                            Rating = 1
                        },
                        new
                        {
                            Id = 37,
                            Comment = "The box this comes in is 3 meter by 5 foot and weights 11 kilogram.",
                            ProductId = 17,
                            Rating = 2
                        },
                        new
                        {
                            Id = 38,
                            Comment = "I saw this on TV and wanted to give it a try.",
                            ProductId = 13,
                            Rating = 4
                        },
                        new
                        {
                            Id = 39,
                            Comment = "i use it once in a while when i'm in my ring.",
                            ProductId = 19,
                            Rating = 5
                        },
                        new
                        {
                            Id = 40,
                            Comment = "This product works extremely well. It wetly improves my tennis by a lot.",
                            ProductId = 16,
                            Rating = 4
                        },
                        new
                        {
                            Id = 41,
                            Comment = "heard about this on new jersey hip hop radio, decided to give it a try.",
                            ProductId = 6,
                            Rating = 2
                        },
                        new
                        {
                            Id = 42,
                            Comment = "My goldfinch loves to play with it.",
                            ProductId = 2,
                            Rating = 5
                        },
                        new
                        {
                            Id = 43,
                            Comment = "i use it every Tuesday when i'm in my store.",
                            ProductId = 4,
                            Rating = 5
                        },
                        new
                        {
                            Id = 44,
                            Comment = "I saw one of these in Algeria and I bought one.",
                            ProductId = 8,
                            Rating = 1
                        },
                        new
                        {
                            Id = 45,
                            Comment = "This product works very well. It romantically improves my football by a lot.",
                            ProductId = 13,
                            Rating = 5
                        },
                        new
                        {
                            Id = 46,
                            Comment = "My co-worker Kazuo has one of these. He says it looks transparent.",
                            ProductId = 13,
                            Rating = 4
                        },
                        new
                        {
                            Id = 47,
                            Comment = "It only works when I'm South Korea.",
                            ProductId = 9,
                            Rating = 5
                        },
                        new
                        {
                            Id = 48,
                            Comment = "i use it every Tuesday when i'm in my pub.",
                            ProductId = 15,
                            Rating = 1
                        },
                        new
                        {
                            Id = 49,
                            Comment = "This product works so well. It imperfectly improves my baseball by a lot.",
                            ProductId = 9,
                            Rating = 5
                        },
                        new
                        {
                            Id = 50,
                            Comment = "The box this comes in is 4 meter by 5 foot and weights 18 kilogram.",
                            ProductId = 19,
                            Rating = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
